<template>
<div class="container terms-page">
<h1><strong>Terms &amp; Conditions - TokenRecap.Com</strong></h1>
<p><span style="font-weight: 400;">Terms And Conditions</span></p>
<p><span style="font-weight: 400;">This is an agreement ("user agreement" or "agreement") between Token Recap Subsidary of Chase Media Inc. &nbsp;(or TokenRecap.Com) ("we", "our," "us") and you. This agreement sets the terms of your use of the TokenRecap.Com website and services - which include our forums and direct messaging. This agreement is meant to encourage a fair and tolerant place for ideas, people, links, and discussion.</span></p>
<p><span style="font-weight: 400;">This agreement is a legal contract between you and us. You acknowledge that you have read, understood, and agree to be bound by the terms of this agreement. If you do not agree to this agreement, you should not use TokenRecap.Com. Please take a look at TokenRecap.Com's Privacy Policy too&mdash;it explains how we collect and use your information.</span></p>
<p><span style="font-weight: 400;">Without advance notice and at any time, we may, for violations of this agreement or for any other reason we choose: (1) suspend your access to TokenRecap.Com, (2) suspend or terminate Your Account or subscription, and/or (3) remove any of your User Content from TokenRecap.Com forums.</span></p>
<p><span style="font-weight: 400;">You are responsible for all use of the Services made using your username and password, whether or not the use is made by you or someone else using your username and password. You are responsible for protecting and securing your username and password from unauthorised use. If you believe there has been a breach of security of your username you should notify TokenRecap.Com. TokenRecap.Com, at its absolute discretion, reserves the right to refuse a user permission to use any particular user name and/or password. It is not permitted to impersonate or to attempt to impersonate another user or to make use of or attempt to make use of another user's user name or password and any such actions may result in legal action, including criminal prosecution.</span></p>
<p><span style="font-weight: 400;">We reserve the right to monitor TokenRecap.Com, and your use of the Service means you agree to such monitoring. At the same time, we do not guarantee we will monitor at all.</span></p>
<p><span style="font-weight: 400;">TokenRecap.Com is designed and supported for personal use only. You may not use TokenRecap.Com to break the law, violate an individual's privacy, or infringe any person or entity&rsquo;s intellectual property or any other proprietary rights.</span></p>
<p><span style="font-weight: 400;">TokenRecap.Com is intended to be a place for your entertainment. We are not responsible for any decisions you make based on something you read on TokenRecap.Com.</span></p>
<p><span style="font-weight: 400;">Crypto Compare is not intended to be a marketplace for any goods or services. For this reason, any transactions you undertake are your responsibility alone, so be careful.</span></p>
<p><span style="font-weight: 400;">You may not use TokenRecap.Com to conduct transactions for any illegal goods or services.</span></p>
<p><span style="font-weight: 400;">To participate on TokenRecap.Com, you must create an account that includes a username and password ("Your Account") and, if you want to be able to reset your password or have us contact you, an email address as well. Of course, you can also browse TokenRecap.Com without logging in.</span></p>
<p><span style="font-weight: 400;">You are solely responsible for the information associated with Your Account and anything that happens related to Your Account.</span></p>
<p><span style="font-weight: 400;">You may not license, transfer, sell, or assign Your Account without our written approval.</span></p>
<p><span style="font-weight: 400;">You retain the rights to your copyrighted content or information that you submit to TokenRecap.Com ("user content") except as described below.</span></p>
<p><span style="font-weight: 400;">By submitting user content to TokenRecap.Com, you grant us a royalty-free, perpetual, irrevocable, non-exclusive, unrestricted, worldwide license to reproduce, prepare derivative works, distribute copies, perform, or publicly display your user content in any medium and for any purpose, including commercial purposes, and to authorize others to do so.</span></p>
<p><span style="font-weight: 400;">You agree that you have the right to submit anything you post, and that your user content does not violate the copyright, trademark, trade secret or any other personal or proprietary right of any other party.</span></p>
<p><span style="font-weight: 400;">Please take a look at TokenRecap.Com's Privacy Policy for an explanation of how we may use or share information submitted by you or collected from you.</span></p>
<p><span style="font-weight: 400;">We take no responsibility for, we do not expressly or implicitly endorse, and we do not assume any liability for any user content submitted by you to TokenRecap.Com.</span></p>
<p><span style="font-weight: 400;">Neither TokenRecap.Com nor any of its Data Providers or affiliates make any warranties expressed or implied, as to the accuracy, adequacy, quality or fitness for any particular purpose of the Information or the Services for a particular purpose or use and all such warranties are expressly excluded to the fullest extent that such warranties may be excluded by law. You bear all risks from any uses or results of using any Information. You are responsible for validating the integrity of any Information received over the Internet. Neither TokenRecap.Com nor its Data Providers or affiliates accept liability for any costs, losses or damages resulting from or related to the availability or content of the Services. The Services or any part do not constitute an offer or solicitation to sell investments in any jurisdiction.</span></p>
<p><span style="font-weight: 400;">You irrevocably indemnify TokenRecap.Com and its Data Providers and affiliates from and against any and all losses, damages and costs suffered or incurred by TokenRecap.Com, any Data Providers or affiliates of whatsoever nature arising out of or in connection with your use, provision or distribution of Information or any part or the Services or any part or otherwise howsoever arising in relation to any breach of this Agreement by you.</span></p>
<p><span style="font-weight: 400;">Due to the number of sources from which TokenRecap.Com obtains content and the nature of electronic distribution via the world wide web neither TokenRecap.Com nor any of its Data Providers nor affiliates have any liability (whether in contract or tort) for any losses, costs or damages resulting from or related to use of or inability to use any Information contained in the Services or the provision of the Services to the fullest extent to which such liability may be excluded or avoided by law and in no event shall TokenRecap.Com be liable to you for lost profits or for indirect, incidental, special, punitive or consequential damages arising out of or in relation to the Services or the provision of Information. TokenRecap.Com makes no warranty that the Service is free from infection by viruses or anything else that has contaminating or destructive properties.</span></p>
<p><span style="font-weight: 400;">Due to the number of sources from which TokenRecap.Com obtains content and the nature of electronic distribution via the world wide web neither TokenRecap.Com nor any of its Data Providers nor affiliates have any liability (whether in contract or tort) for any losses, costs or damages resulting from or related to use of or inability to use any Information contained in the Services or the provision of the Services to the fullest extent to which such liability may be excluded or avoided by law and in no event shall TokenRecap.Com be liable to you for lost profits or for indirect, incidental, special, punitive or consequential damages arising out of or in relation to the Services or the provision of Information. TokenRecap.Com makes no warranty that the Service is free from infection by viruses or anything else that has contaminating or destructive properties.</span></p>
<p><span style="font-weight: 400;">TokenRecap.Com is a place with many third-party hyperlinks posted by users like you. We are not responsible for the content or actions of any third party websites or services associated with posted links. You agree to take sole legal responsibility for any links you post, and neither this agreement nor our privacy policy applies to any content on other websites related to those links. You should consult the terms and privacy policies of those other websites to understand your rights.</span></p>
<p><span style="font-weight: 400;">You also agree to follow the TokenRecap.Com's Content policy. These guidelines are intended to keep people safe, protect kids, keep TokenRecap.Com running, and to encourage personal responsibility for what you do on TokenRecap.Com.</span></p>
<p><span style="font-weight: 400;">You may not post any graphics, text, photographs, images, video, audio or other material that we deem to be junk or spam. Cluttering TokenRecap.Com with this sort of content reduces the quality of the TokenRecap.Com experience for others. We reserve the right to determine what spam is and to delete it for the benefit of users. If you feel you content has been deleted unfairly you have the chance to email us with your reasons why. You may not post your own affiliate links on the site.</span></p>
<p><span style="font-weight: 400;">You agree not to interrupt the serving of TokenRecap.Com, introduce malicious code onto TokenRecap.Com, make it difficult for anyone else to use TokenRecap.Com due to your actions, or assist anyone in misusing TokenRecap.Com in any way.</span></p>
<p><span style="font-weight: 400;">TokenRecap.Com is not directed at people under the age of 13, and TokenRecap.Com does not knowingly collect any personal information from such people. If you know that a user under the age of 13 is accessing TokenRecap.Com, please contact us at vegeta@TokenRecap.Com.</span></p>
<p><span style="font-weight: 400;">TokenRecap.Com (Token Recap Subsidary of Chase Media Inc. ), at our discretion, provide you with services including, but not restricted to, news and information services. You agree to comply with the conditions imposed on your use of the services, as set out in these Terms and Conditions of Access and elsewhere in our services. These services may be outside our control or provided by a third party in which in case we cannot take responsibility for their content, or for any delays, interruptions or errors in the provisions of these additional services, provided we have exercised reasonable care and diligence in the selection of such providers.</span></p>
<p><span style="font-weight: 400;">Certain data accessible on our services is the intellectual property of the relevant news and information services provider or third parties that provide such data to the relevant service provider, or us. The data is protected by copyright and other intellectual laws and all ownership rights remain with the information service provider or the third party or us, as the case may be.</span></p>
<p><span style="font-weight: 400;">The data is provided "as is". We, any information service provider or any third party shall not be liable to you or any third party for any loss or damage, direct, indirect or consequential, arising from (i) any inaccuracy or incompleteness in, or delays, interruptions, errors or omissions in the delivery of the data or any other information supplied to you through our services or (ii) any decision made or action taken by you or any third party in reliance upon the data. Nor shall we, any information service provider or any third party be liable for loss of business revenues, lost profits or any punitive, indirect, consequential, special or similar damages whatsoever, whether in contract, tort or otherwise, even if advised of the possibility of such damages incurred by you or any third party.</span></p>
<p><span style="font-weight: 400;">Where the information consists of pricing or performance data, the data contained therein has been obtained from sources believed reliable. Data computations are not guaranteed by any information service provider, third party or us or any affiliates and may not be complete. Neither we, any information service provider, nor any third party give any warranties, as to the accuracy, adequacy, quality or fitness, timeless, non-infringement, title, of any information for a particular purpose or use and all such warranties are expressly excluded to the fullest extent that such warranties may be excluded by law. You bear all risk from any use or results of using any information. You are responsible for validating the integrity of any information received over the Internet.</span></p>
<p><span style="font-weight: 400;">Transmission may be subject to arbitrary delays beyond our control, which may delay the provision of our services and the execution of your orders. You acknowledge that neither we, any information service provider, nor any third party will be liable to you or any third party for any losses arising from such delay.</span></p>
<p><span style="font-weight: 400;">In no event will we, any information provider, or third party be liable for any consequential loss including but not limited to special, incidental, direct or indirect damages resulting from delay or loss of use of our services. We are not responsible for any damage to your computer, software, modem, telephone or other property resulting from your use of our services.</span></p>
<p><span style="font-weight: 400;">Any claim or dispute between you and us arising out of or relating to this user agreement, in whole or in part, shall be governed by the laws of the United States.</span></p>
<p><span style="font-weight: 400;">If any provision of this user agreement is held invalid or unenforceable, that provision will be modified to the extent necessary to render it enforceable without losing its intent. If no such modification is possible, that provision will be severed from the rest of this agreement.</span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">This user agreement is the entire agreement between you and us concerning TokenRecap.Com. It supersedes all prior or contemporaneous agreements between you and us. We may modify this user agreement at any time. If we make changes to this agreement that materially affect your rights, we will provide advance notice and keep this edition available as an archive on the TokenRecap.Com website. By continuing to use TokenRecap.Com after a change to this agreement, you agree to those changes.</span></p>
<h1><br /><br /></h1>
</div>
</template>